#installing httpd 
- name: installing
  hosts: local
  remote_user: root
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: '{{gather}}'
  vars:
    gather: true
    package: httpd
  tasks:
  - name: Install the indicated softwaer
    apt-get:
      name: '{{ package }}'
      state: latest

	  
	  
-name: Automated Test to check whether web server is up or not
 wait_for:
    port:8000
    delay:10